name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOK }}
      run: |
        npm install @angular/cli
        cd ./src
        cp ./src/environments/environment.sample.ts ./src/environments/environment.ts
        cp ./src/environments/environment.sample.ts ./src/environments/environment.prod.ts
        npm ci
        npm run ng -- deploy --base-href=/City_past_frontend/
